### ISSUE TITLE
Support two backport labels

### ISSUE THREAD

**Issue by bk201** [harvester/bot#11]
The bot has a chance not to create two backport issues, e.g. https://github.com/harvester/harvester/issues/4432

**Comment by bk201** [comment]
And the bot could create backport issue for back issues: https://github.com/harvester/harvester/issues/2427 -> https://github.com/harvester/harvester/issues/5198 -> https://github.com/harvester/harvester/issues/5199 -> https://github.com/harvester/harvester/issues/5200

**Comment by Yu-Jack** [comment]
Another issue is we could add backport label in backport issue, it should not be allowed technically.

**Comment by Yu-Jack** [comment]
@bk201  I think this one is done, so I'll close it.
